### ISSUE TITLE
override groupByFieldsForStatistics in winnow

### ISSUE THREAD

**Issue by keithfraley** [koopjs/winnow#102]
we are dealing with very large datasets.  These large data sets need the field stats calculated at the server level, not at a winnow level. We are interested in doing groupby stats against possible tens of thousands of different unique field values.

I can easily do this and mirror the necessary response the client is expecting in arcgis, however the stats are getting calculated again in winnow (i think?) and thus the wrong counts are provided (usually a count of 1 or 0) is there a way to easily request winnow to except the values provided by the geojson as the correct field stats?

**Comment by rgwozdz** [comment]
Once you use the req.query.groupByFieldsForStatistics in the provider, you could delete it from the `req.query` object:

 ```
delete req.query.groupByFieldsForStatistics
```

That way it won’t be around for Winnow and FeatureServer to process.
