### ISSUE TITLE
High volumes of requests cause date queries to break

### ISSUE THREAD

**Issue by efbenson** [koopjs/winnow#108]
I am thinking this is where the issue would go.  When we are in prod, ~4 million requests a day across 3 instances, there are cases where date queries return 0 results.  You can keep querying over and over though koop (using querystrings generated by AGOL) and once and a while (frequency tied to loading) you get 0 results, even with no changes in data (running out of koop's memory cache).  This does not happen with string or number data based queries.  I am doing my best to try and run down the issue myself, but any ideas would be helpful.

Sample where: eta>timestamp '2019-01-01 04:59:59'
queryString: ```query?f=json&where=eta%3Etimestamp%20%272019-01-01%2004%3A59%3A59%27&returnGeometry=false&spatialRel=esriSpatialRelIntersects&outFields=*&outSR=102100&resultOffset=0&resultRecordCount=25```

**Comment by johngalambos** [comment]
I'm getting this behavior on any request after the first one as long as the default cache is turned on. I suspect there's something going with the types of the date attributes flipping between ISO strings in the first geojson getData method and integers in the cache. Continuing to dig into it, but if you ever did get to the bottom of this, I'd appreciate some pointers!

**Comment by rgwozdz** [comment]
@johngalambos Read this whole [thread](https://github.com/koopjs/koop/issues/358) and especially [my last comment](https://github.com/koopjs/koop/issues/358#issuecomment-594205838).

**Comment by rgwozdz** [comment]
This has been fixed with changes in the way we do caching.
