### ISSUE TITLE
Esri envelope geometry option converted to invalid GeoJSON polygon

### ISSUE THREAD

**Issue by nheminger** [koopjs/winnow#110]
An Esri envelope option specified to Winnow is normalized to a GeoJSON Polygon incorrectly.

Input of envelope:

`{"xmin":-180,"ymin":-180,"xmax":0,"ymax":0,"spatialReference":{"wkid":4326,"latestWkid":4326}}`

Results in a geometry inside sql.js of:

`{"type":"Polygon","coordinates":[[[-180,-180],[-180,0],[0,0],[0,-180],[-180,-180]]]}`

This geometry does not validate according to [http://geojsonlint.com/](http://geojsonlint.com/) because it is clockwise.

[GeoJSON IETF RFC 7946](https://tools.ietf.org/html/rfc7946#section-3.1.6) section _3.1.6. Polygon_ specifies a counter-clockwise order of coordinates for exterior polygon rings:

> A linear ring MUST follow the right-hand rule with respect to the
> area it bounds, i.e., exterior rings are counterclockwise, and
> holes are clockwise.
> 

The order of coordinates in [transform-envelope.js](https://github.com/koopjs/winnow/blob/master/src/geometry/transform-envelope.js) could use adjusting to be compliant with the RFC. This will enable better validation of the GeoJSON and any tests on them.

**Comment by rgwozdz** [comment]
Released fix in v 1.16.6.
