### ISSUE TITLE
Any spatial indexing like rtree, btree, rbush was used?

### ISSUE THREAD

**Issue by hoogw** [koopjs/winnow#132]
I am new to koop.js

Any spatial indexing like rtree, btree, rbush was used in winnow?

    for example: 

        terraformer.js use rtree
        sqlite  use rtree
       sql server spatial use btree
       oracle use ?
       postgis use ?

I have not test yet,     
How the spatial query performance is? Would rtree make it faster?

**Comment by rgwozdz** [comment]
Not to my knowledge.  It uses alasql to do all processing on data held in memory.

**Comment by hoogw** [comment]
alasql use 'in memory' should be fast compare to indexedDB, sqlite (store on disk, physical file), I am going to test the spatial query performance with 1m features geojson ST_interact. 

terraformer.js is so fast with polygon interact , without delay

**Comment by hoogw** [comment]
so far failed to build a browser version of winnow.js.
no way to test it in browser

see my another issue for failure with browserify

**Comment by rgwozdz** [comment]
This wasn't developed with the browser in mind, but if you want to try a PR, feel free.

**Comment by hoogw** [comment]
browser version have great use case than server version. I am using terraformer.js browser version for now.  Winnow could be a good alternative to that.
