### ISSUE TITLE
Polygons are projected incorrectly

### ISSUE THREAD

**Issue by dmfenton** [koopjs/winnow#50]
Add a unit test for projecting a polygon from WGS84 to NAD83 and Web Mercator

**Comment by rgwozdz** [comment]
Added additional polygon projection tests for conversion of WGS84 to NAD83 in 5ba3ada345f066de251fb470f9e7c1031bde2405.  Observed that adding `toEsri: true` to options causes a rewinding of polygon coordinates in the clockwise direction.
