### ISSUE TITLE
Ordering is broken

### ISSUE THREAD

**Issue by efbenson** [koopjs/winnow#84]
https://github.com/koopjs/winnow/blob/5ba3ada345f066de251fb470f9e7c1031bde2405/src/executeQuery.js#L64

Because the way that this is implemented and querying per feature vs against all of them order does not work.  I am happy to do a PR to fix this, however I need some direction.  I think the cleaner way would be to run the query against all the features so you get proper order and limiting/skipping but I don't know if there was a reason for one offing the queries.  The other option is to build out a custom (or use some lib) to do ordering on the data outside of alasql.

**Comment by efbenson** [comment]
Looking into some options nothing looks real easy.  I see the issue is with the special date field needing be remapped from the source feature to the filtered and there is no way to associate the 2.  I'll give a shot on a post query sort.

**Comment by efbenson** [comment]
Covered in #85

**Comment by rgwozdz** [comment]
Moved ordering and esriFy to SQL in https://github.com/koopjs/winnow/pull/90; released in v1.16.1.
