### ISSUE TITLE
Can not install recent versions that include flora-sql-parser with --no-bin-links

### ISSUE THREAD

**Issue by efbenson** [koopjs/winnow#87]
We cannot use symlinks for our build and deploy process so we cannot use the most recent version of winnow.  I have created a PR for that project https://github.com/godmodelabs/flora-sql-parser/pull/21  hopefully they merge it (or another fix) and you can bump the dependancy.

**Comment by rgwozdz** [comment]
Looks like this was fixed https://github.com/godmodelabs/flora-sql-parser/pull/21.
